#
# Copyright (c) 2006-2025 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - https://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        unblockui:
            enable: true
            category: "Misc"
            name: "UnBlockUI"
            description: "This module removes all jQuery BlockUI dialogs."
            authors: ["bcoles"]
            target:
                user_notify: ["ALL"]
